compile:
	javac Customer.java GST.java RestaurantApplication.java RestaurantOwner.java

run:
	java  RestaurantApplication 

clean:
	del Customer.class RestaurantApplication.class RestaurantOwner.class GST.class Operations.class